language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_install:
  - sudo apt-get update
  - sudo apt-get install -y php5-gd
install:
  - composer install

script:
  - bin/phpunit test